### ISSUE TITLE
Tapestry API Caching - pluggable

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#21]
We can speed up performance massively by hooking up an in memory Cache of the requests made my Tapestry's proxy.

I'd like to have a nose around other server projects, and see how people are providing a plug-in-able  caching service. A fast key/value store where `url: response` is stored by Tapestry is the end-goal.

**Comment by ecoad** [comment]
If WireHive setup the hosting environment of Tapestry and Foundry sweetly then it may well be that the Nginx cache on Foundry is suitable.

Rather than requests going over the internet for `shortliststudio.foundry.press`, the DNS is routed locally within our VPC for super sweet perf? The advantage here being that you're maintaining fewer caching layers.

If you were to use Redis, you're still going over the network (albeit within the same VPC) to get your key/value store. And you do need a server as it manages stale caches, memory allocation, invalidation etc, and is often setup for horizontal scalability.

**Comment by jonsherrard** [comment]
https://github.com/shortlist-digital/tapestry-wp/pull/89 adds this - also HTML render caching for sweet sweet speed.
