### ISSUE TITLE
Error or NotFound component

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-wp#47]
We need to surface the ability to override the default 404 page, we could add an optional `<NotFound />` component to the `tapestry.config.js`.

I'm not sure how we'd handle and server errors, non-matched routes etc. anything that doesn't run through ReactRouter.

**Comment by jonsherrard** [comment]
OK ill kick off without having tried any of this - as I understand it:

After registering static files, proxies, and the API - Everything in Hapi should route to react router.

React router will not match on certain patterns and render the not found component.

The second bit is slightly harder, what happens when a path matches but the API responds with a 404?  the loader should detect the status and render the not found component - or maybe an error component that accepts status and reason as props.

This solution adds weight to the concept of having a single, easily configurable data loader. Otherwise the data loading step is going to have a lot of repeated code.

**Comment by thomasdigby** [comment]
We've got a check in already for a 404ing API so it's definitely doable. I think a generic Error component could work well, we could pass back status code, error message etc.

We'll probably need to break out the data-loader & the HTML rendering into their own modules as we'll need to run `<Error />` through the same renderer as the other components. We'll need to use the `renderStaticOptimized`, `renderToString`, `renderToStaticMarkup` etc.

I assume we'll also still need to call `<AsyncProps />` or can we pass through the component directly?

**Comment by jonsherrard** [comment]
Closed by #69
